const abusiveWords = [
    "kiss",
    "Bitch",
    "bitch",
    "nigga",
    "Stupid",
    "stupidity",
    "fuck",
    "kill",
    "pagal",
    "stupid",
    "darling",
    "marry",
    "sexy",
    "sexy",
    "sexyyy",
    "sexyyy",
    "sexyyy",
    "sultry",
    "sultry",
    "SULTRY",
    "Sultry",
    "sultryyy",
    "sultryyy",
    "sultryyy",
    "hottie",
    "hottie",
    "HOTTIE",
    "Hottie",
    "hottieee",
    "hottieee",
    "hottieyy",
    "naughty",
    "bae",
    "bae",
    "BAE",
    "Bae",
    "baeee",
    "baeee",
    "baeyy",
    "boo",
    "boo",
    "BOO",
    "Boo",
    "boooo",
    "boooo",
    "nigger", "faggot", "fag", "dyke", "tranny", "retard",
    "chink", "kike", "spic", "wetback", "gook", "towelhead",
    "raghead", "sandnigger", "beaner", "cunt", "paki",
    "slut", "whore", "cum", "cumslut", "fuckhole", "cocksucker",
    "twat", "pussy", "dick", "blowjob", "asshole", "fcuk",
    "jerk", "jerkoff", "jackoff", "wank", "wanker", "fap",
    "kys", "killyourself", "killurself", "diealready", "gokill",
    "gohangurself", "shootyou", "rapeyou", "illkill", "illhurt",
    "stab", "murder", "strangle", "torture", "bash", "smash",
    "idiot", "moron", "dumbass", "dumbo", "imbecile", "loser",
    "fool", "pathetic", "worthless", "useless", "failure", "scum",
    "trash", "garbage", "waste", "disgrace", "ugly", "fatso",
    "fatty", "disgusting", "gross", "creep", "stalker", "perv",
    "pervert", "sicko", "psycho", "insane", "lunatic",
    "fuckyou", "fucku", "fku", "motherfucker", "stfu", "gtfo",
    "shutup", "gofuckyourself", "ihateyou", "youresodumb",
    "pieceofshit", "pos", "nolife", "kys", "kms",
    "beautiful", "gorgeous", "cute", "handsome", "pretty",
    "wifey", "hubby", "girlfriend", "boyfriend", "love",
    "lover", "crush", "dating", "smooch", "hugs",
    "kisses", "xoxo", "makeout", "makeoutwith", "sex",
    "sexting", "sexytime", "naked", "nude", "nudes",
    "sendnudes", "pics", "sendpics", "snapme",
    "sexxy", "sexxxy", "sexi", "sexxi", "sexxxi",
    "hott", "hotttt", "hawt", "hawtt",
    "babee", "babyy", "babby", "bby",
    "sweetypie", "sweetiepie", "honeybun", "sugarpie",
    "foxxy", "foxxxy", "cutiepatootie", "cutiepie",
    "sweetums", "snuggle", "snuggles", "huggable"
];
const abusiveWordsSet = new Set(abusiveWords);

export { abusiveWordsSet };